version: "3.3"

services:
#  database:
#    image: postgres
#    container_name: database
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=docker
#      - POSTGRES_PASSWORD=desafio
#      - POSTGRES_DB=inovaico
#    volumes:
#      - pgdata:/data/postgres
#    network_mode: host
  app:
    build: .
    container_name: desafio
    ports:
      - "3333:3333"
    volumes:
     - .:/usr/app
     
volumes:
  pgdata:
    driver: local
